### ISSUE TITLE
New release for Django 1.8 compatibility

### ISSUE THREAD

**Issue by Gagaro** [zyga/django-pagination#29]
Hi,

Is a release on pypi planned ?

I'm migrating an app to Django 1.8 and have to get the app from git at the moment.

Thanks

**Comment by zyga** [comment]
Hey.

I entirely stopped releasing this to pypi. AFAIR there was an unclean
situation with the original developer owning the project on pypi. If you
have any idea how to resolve that situation then I'm all ears and I could
use the help. Personally I'm not using the pagination code anymore so I
don't maintain it actively.

2015-06-30 15:32 GMT+02:00 Gagaro <notifications@github.com>:

**Comment by Gagaro** [comment]
What kind of situation are you talking about ?

Is it that you can't or you don't want to release ?

I found [this](http://stackoverflow.com/q/20732179/2575355) about taking ownership of dead packages, so it may seems possible to take it if the original owner doesn't want to maintain it anymore.

**Comment by zyga** [comment]
I'm willing to release but I don't have upload rights on pypi under the
name 'django-pagination'. Historically I did release
linaro-django-pagination (checking if I can still do that -- yes). So if
you are okay with me releasing linaro-django-pagination I can do that in a
moment.

2015-07-01 11:05 GMT+02:00 Gagaro <notifications@github.com>:

**Comment by Gagaro** [comment]
Yes I have no problem using linaro-django-pagination (I'm already using it).

**Comment by zyga** [comment]
Cool, I'm heading home now. I'll release l-d-p in an hour.                                                                                                                                                                                                                                                                                                                                        Enviado desde mi smartphone BlackBerry 10.                                                                                                                                                                                                                De: GagaroEnviado: Wednesday, 1 July 2015 12:37Para: zyga/django-paginationResponder a: zyga/django-paginationCC: Zygmunt KrynickiAsunto: Re: [django-pagination] New release for Django 1.8 compatibility (#29)Yes I have no problem using linaro-django-pagination (I'm already using it).

—Reply to this email directly or view it on GitHub.

**Comment by Gagaro** [comment]
Awesome, thanks a lot!

**Comment by Gagaro** [comment]
Hi @zyga, did you forgot about this ? :grinning:

**Comment by zyga** [comment]
Yes, doing this now :)

2015-07-06 13:40 GMT+02:00 Gagaro <notifications@github.com>:

**Comment by zyga** [comment]
Done.

Though the problem is that tests fail. I spent a moment trying to unbreak
them but it seems this is related to ongoing changes to django and I'd have
to go and fix django-testproject first. Contributions welcome!

Thanks
ZK

2015-07-06 14:49 GMT+02:00 Zygmunt Bazyli Krynicki <zkrynicki@gmail.com>:

**Comment by Gagaro** [comment]
Thanks for the release :+1: 

With which version of Django are you running the tests ? I had to modify the test_project files to get it running on 1.8 and some of the tests fails (see https://github.com/Gagaro/django-pagination/commit/964f8b3d72904e69572d6c1e1d45c4741a36bb4c).

**Comment by Gagaro** [comment]
Maybe we should open another issue to talk about this.

**Comment by Gagaro** [comment]
https://github.com/zyga/django-pagination/issues/30

**Comment by zyga** [comment]
Latest from pypi (I just ran ./setup.py test)

Yeah. This should be a new issue.

2015-07-06 15:57 GMT+02:00 Gagaro <notifications@github.com>:
