### ISSUE TITLE
The tests are not working

### ISSUE THREAD

**Issue by Gagaro** [zyga/django-pagination#30]
Continued from https://github.com/zyga/django-pagination/issues/29

**Comment by Gagaro** [comment]
I'm not really up to date with doctests, shouldn't the following test successes ?

```
Expected:
    u'\n...\n...<div class="pagination">...
Got:
    u'\n\n<div class="pagination">\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  <span class="current page">1</span>\n  \n  \n  \n  \n  \n  \n  <a href="?page=2" class="page">2</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=3" class="page">3</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=4" class="page">4</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=5" class="page">5</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=6" class="page">6</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=7" class="page">7</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=8" class="page">8</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=9" class="page">9</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=10" class="page">10</a>\n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=11" class="page">11</a>\n  \n  \n  \n  \n  \n  \n  \n  \n  <a href="?page=2" class="next">next &rsaquo;&rsaquo;</a>\n  \n  \n</div>\n\n'
```

**Comment by zyga** [comment]
Tests seem to be broken with all the changes to django/testtools. For context, I've been running tests with setup.py test all the time and in the ancient old days when this worked, it did (django 1.2) perhaps some new approach is needed.

**Comment by Gagaro** [comment]
Using TestCase instead of doctests should be a good start.

**Comment by zyga** [comment]
Doctests should be converted to a TestCase / unittest system. There are
several ways of doing that (easy to harder). Django stopped running those
by default since 1.4 from what I read.

2015-07-06 16:22 GMT+02:00 Gagaro <notifications@github.com>:
