### ISSUE TITLE
linaro-django-pagination gone from PyPI

### ISSUE THREAD

**Issue by V-Alexeev** [zyga/django-pagination#31]
The PyPI page for linaro-django-pagination (https://pypi.python.org/pypi/linaro-django-pagination/)  shows 404 at the moment. Judging by Google cache the page was available a week ago. What has happened?

**Comment by zyga** [comment]
I'll check it out and upload again if needed                                                                                                                                                                                                                                                                                                                                        Enviat des del meu telèfon intel·ligent BlackBerry 10.                                                                                                                                                                                                                De: Vasily AlexeevEnviat: Monday, 28 September 2015 14:36Per a: zyga/django-paginationRespon a: zyga/django-paginationTema: [django-pagination] linaro-django-pagination gone from pypi (#31)The PyPI page for linaro-django-pagination (https://pypi.python.org/pypi/linaro-django-pagination/)  shows 404 at the moment. Judging by Google cache the page was available a week ago. What has happened?

—Reply to this email directly or view it on GitHub.

**Comment by sylvainb** [comment]
+1

**Comment by chesstrian** [comment]
:+1:

**Comment by Laisky** [comment]
Still 404 now,

**Comment by zyga** [comment]
Fixed. I'm sorry for the extreme lag.

**Comment by sylvainb** [comment]
The latest release (2.1) seems not available on pypi

**Comment by zyga** [comment]
Hmmm, let's see, my master was at 2.0.3, not at 2.1

**Comment by sylvainb** [comment]
Ok, it's 2.1 in the release GitHub page
